DROP TABLE IF EXISTS tabela_1;
DROP TABLE IF EXISTS tabela_2;
DROP TABLE IF EXISTS tabela_3;
DROP TABLE IF EXISTS tabela_4;
DROP TABLE IF EXISTS tabela_5;

CREATE TABLE IF NOT EXISTS tabela_1 (
	id SERIAL PRIMARY KEY NOT NULL
);
CREATE TABLE IF NOT EXISTS tabela_2 (
	id SERIAL PRIMARY KEY NOT NULL
);
CREATE TABLE IF NOT EXISTS tabela_3 (
	id SERIAL PRIMARY KEY NOT NULL
);
CREATE TABLE IF NOT EXISTS tabela_4 (
	id SERIAL PRIMARY KEY NOT NULL
);
CREATE TABLE IF NOT EXISTS tabela_5 (
	id SERIAL PRIMARY KEY NOT NULL
);
